jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}


management:
  endpoints:
    web:
      exposure:
        include: '*'